version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - "5488:5432"
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
       - db-data:/var/lib/postgresql/data

volumes:
  db-data: